sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
before_install:
  - npm install @alrra/travis-scripts
  - npm run auth
script:
  - npm run build:ci
after_success:
  - npm run deploy:staging
  - npm run deploy
