sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
before_install:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_6b7ea0692d18_key -iv $encrypted_6b7ea0692d18_iv -in deploy_key.enc -out /tmp/deploy_key -d
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
  - openssl aes-256-cbc -K $encrypted_68be772c97c4_key -iv $encrypted_68be772c97c4_iv -in install_key.enc -out /tmp/install_key -d
  - chmod 600 /tmp/install_key
  - ssh-add /tmp/install_key
script:
  - npm run build-ci
after_success:
  - npm run deploy-staging
  - npm run deploy
