sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
before_install:
  - echo -e "Host github.com\n\tIdentityFile /tmp/deploy_key\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_6b7ea0692d18_key -iv $encrypted_6b7ea0692d18_iv -in deploy_key.enc -out /tmp/deploy_key -d
script:
  - npm run build-ci
after_success:
  - npm run deploy-staging
  - npm run deploy
