sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
script:
  - STATICS='--src-statics node_modules/sinnerschrader-website-static/statics' npm run build
after_success:
  - npm run deploy-staging
  - npm run deploy
