sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
script:
  - npm run taint
  - npm run build
after_success:
  - npm run deploy-staging
  - npm run deploy
